### ISSUE TITLE
Feature request: Prompt weight control hotkey

### ISSUE THREAD

**Issue by Miraihi** [DrCyanide/cyanic-sd-krita#16]
A followup to "lora selector". While it's not exactly hard to put some parenthesis and the weight the old-fashioned way, it'll be nice to have the hotkey like in Automatic1111 UI (Ctrl + up/down) to change the weight of a certain token.

**Comment by DrCyanide** [comment]
I'm going to put this down as a hard "no" because 1) I don't want to accidentally intercept hotkeys intended for Krita and 2) I was always irritated when I accidentally triggered that feature in the WebUI.
