### ISSUE TITLE
Can't see the textual inversion list in "Extra networks"

### ISSUE THREAD

**Issue by Miraihi** [DrCyanide/cyanic-sd-krita#19]
The title. I see the list of LorA's completely fine, but not embeddings. As a little experiment I've made a symlink for "embeddings" folder and put in into "stable-diffusion-webui/models" and now it works. Seems like you've used the SD.Next folder structure. By default the "embeddings" folder is situated in the root folder of `stable-diffusion-webui`.

**Comment by DrCyanide** [comment]
I don't look at the folder structure, I'm only using what the API returns from `/sdapi/v1/embeddings`. I tested this with A1111 while developing, and my embeddings worked from the `stable-diffusion-webui/embeddings` folder. 

I'd need more information to figure out if it was an issue with A1111 or some delay in the plugin updating, but it shouldn't be a folder issue. If you delete the symlink, and the issue returns, report it to A1111.

**Comment by Miraihi** [comment]
Alright, I've deleted the symlink.
The problem somehow fixed itself. Maybe it needed some kind of warmup launch.
