### ISSUE TITLE
Inpaint not passing the image in the Results folder

### ISSUE THREAD

**Issue by rexelbartolome** [DrCyanide/cyanic-sd-krita#24]
Img2Img works fine though

https://github.com/DrCyanide/cyanic-sd-krita/assets/88552647/c82d9d11-e59d-43f4-9943-3b49a690b6f6

[log-dragon-inpaint.json](https://github.com/DrCyanide/cyanic-sd-krita/files/13437823/log-dragon-inpaint.json)

**Comment by DrCyanide** [comment]
Fixed it. Some changes I made yesterday to try and get RemBG results in the right spot if the source image was in a group accidentally broke the Inpainting position.
