### ISSUE TITLE
Integration with Easy Diffusion

### ISSUE THREAD

**Issue by CHJ85** [DrCyanide/cyanic-sd-krita#27]
Hi there. Please add Easy Diffusion integration.
https://github.com/easydiffusion/easydiffusion
Thanks.

**Comment by DrCyanide** [comment]
Easy Diffusion doesn't have a public-facing API, and from what I am reading doesn't intend to add one. When someone asked a similar question, it was suggested that they write an "sdkit" extension for Easy Diffusion to accomplish the task instead.

https://github.com/easydiffusion/easydiffusion/issues/1346

If you can find an SDKit for Easy Diffusion (or write your own) that emulates the A1111 API then this project should be compatible. I'd be interested in knowing if such a way to modify Easy Diffusion exists and sharing it with others, however, I'm drawing my limit at supporting A1111 and SD.Next.

**Comment by CHJ85** [comment]
I see. I wouldn't even know where to get started doing that. Guess I should just install Automatic 1111.
