### ISSUE TITLE
Feature Request: txt2img ControlNet Mask for Inpaint Only + Lama

### ISSUE THREAD

**Issue by duskydd** [DrCyanide/cyanic-sd-krita#28]
https://github.com/Mikubill/sd-webui-controlnet/discussions/1597

Hi, I wondering if it is possible to add this ControlNet feature to the krita plugin since I don't see an option to add a mask in txt2img and img2img similarly to A1111. Not if this falls under "not supported" category since the feature can also used for outpainting.

**Comment by DrCyanide** [comment]
I think this is actually already supported, but I'll let you tell me if this works for you (I'm not getting great results in either the Web UI or in Krita, but I am getting results).

I don't think you need a _mask_ for this ControlNet model to work, but rather a starting image. There's an option to select that image based on either your current selection, your active layer, or the whole canvas.
![ControlNet Selection Types](https://github.com/DrCyanide/cyanic-sd-krita/assets/13542136/82c73e2f-68bc-49b0-9ba0-f9b1396cc739)

In my test, I had pasted in the image as a new layer, so I selected that layer in ControlNet. (I was re-using the image from my Web UI testing, you can achieve a similar effect by drawing a selection box before your first Txt2Img.) I set my ControlType to Inpaint and set all the other settings like I found in a tutorial on Inpaint only + Lama. (Someone reported a bug where the scrollbars don't show up in the dropdowns, so if you don't see Inpaint as an option and you don't see the scroll bar, try using your middle mouse button to scroll anyway).

Cyanic SD will set the Txt2Img generation size as whatever your canvas is _or_ whatever your selected area is. So setting the canvas size or making a selection box acts the same as setting the Width and Height in Automatic 1111.  I made a selection that matched the height of my layer, and clicked generate.

Here's the results I got. Not great, but obviously outpainted by ControlNet

![ControlNet Inpaint+Lama](https://github.com/DrCyanide/cyanic-sd-krita/assets/13542136/1ec5f8ee-ac06-4fa3-bec9-ea850234de0b)

**Comment by duskydd** [comment]
Thanks for the help! I was able to get the outpainting feature working fairly similarly to the webui but I wasn't able to figure how to use this controlnet to remove objects for the plugin.

**Comment by DrCyanide** [comment]
Ah, now I understand! I don't think I've ever needed to use the mask feature in ControlNet before, so I just ignored it.

I'll have to think about how to implement ControlNet masks in the UI, but it could be a quick fix.

**Comment by duskydd** [comment]
Thanks in advance!

**Comment by DrCyanide** [comment]
Minor update: It's going to be more annoying than I thought. I have the UI coded up, but ControlNet is more particular about the format for the mask than Stable Diffusion is. The masks I've been giving to Stable Diffusion aren't compatible with ControlNet, so I've got to figure out a way to convert them into a format that ControlNet will be happy with. I believe this is because the masks I'm generating are monochromatic (just black or white), while the masks that ControlNet wants are technically full color (even if they only use the black or white).

**Comment by DrCyanide** [comment]
Looks like I already had the conversion code laying around from some other ControlNet features. 
![image](https://github.com/DrCyanide/cyanic-sd-krita/assets/13542136/23cfdf72-4ea7-4b3f-8eeb-05e335001a3f)
Added a checkbox above the image selection box to toggle to Mask mode, which works the same way as the Inpainting masks - The active layer will be treated as the mask, with the colored areas being selected, and the image below the mask will be sent as the non-masked image.

This is pushed, go ahead and give it a try.

**Comment by duskydd** [comment]
The UI is bit cluttered or overlaps when I enable "use mask" which isn't too much of a problem. 
![clutter](https://github.com/DrCyanide/cyanic-sd-krita/assets/152806990/3890d5a8-bf40-41d0-a46f-22184f8c4cc1)

Thanks a lot for implementing it! It's working very well for me.

**Comment by DrCyanide** [comment]
Yeah... the overlap is a bug caused by having an animation for the collapsing categories (like Mask Settings, Inpaint Settings, Extensions, etc). I'll probably take out the animation at a later date to fix it.

**Comment by DrCyanide** [comment]
> The UI is bit cluttered or overlaps when I enable "use mask" which isn't too much of a problem. ![clutter](https://private-user-images.githubusercontent.com/152806990/290358223-3890d5a8-bf40-41d0-a46f-22184f8c4cc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNzgxNTUsIm5iZiI6MTcwNDM3Nzg1NSwicGF0aCI6Ii8xNTI4MDY5OTAvMjkwMzU4MjIzLTM4OTBkNWE4LWJmNDAtNDFkMC1hNDZmLTIyMTg0ZjhjNGNjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxNDE3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmNiYmI3YTFjNWE1ZGIyZTEyYTkxNGFhYmU4YWM5OTU2MjA5ODA3ZGM1OWExZDkyNTFhMGI0NGVmMWJmOWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sL2Eba-d_Hi1G_CJ9p47h-Qt4D2-HPmgCP3lrzJWSaE)

This UI overlapping bug should be fixed now.
