### ISSUE TITLE
How can I use soft inpainting?

### ISSUE THREAD

**Issue by pinea00** [DrCyanide/cyanic-sd-krita#32]
How can I open soft inpaint function like A1111 Ver1.8? Thanks

**Comment by DrCyanide** [comment]
I wasn't even aware of Soft Inpainting until you mentioned it. The API looks straight forward, so it shouldn't take too long to add.

**Comment by pinea00** [comment]
This is a useful function,update,please
thank you very much.

**Comment by DrCyanide** [comment]
![image](https://github.com/DrCyanide/cyanic-sd-krita/assets/13542136/4981b471-501c-473c-9f2a-0863bada87a7)
Soft inpainting should now be available in the Inpaint tab. I don't think I got my personal settings for it dialed in enough get the full effect, but it has all the settings to dial it in and it matches what the API expects.
