### ISSUE TITLE
Generate Image with Inpaint and controlnet does not give generated image in layer

### ISSUE THREAD

**Issue by Socheath-Horl** [DrCyanide/cyanic-sd-krita#33]
When I generate Image with Inpaint and openpose controlnet, it doesn't give me the generated image in layer, but it give me the skeleton image in layer instead.
![Screenshot 2024-04-10 223430](https://github.com/DrCyanide/cyanic-sd-krita/assets/106974033/b330cbd0-15ed-4215-884d-c22a7a09bc8e)
![Screenshot 2024-04-10 224331](https://github.com/DrCyanide/cyanic-sd-krita/assets/106974033/294096b2-d9f3-4d0d-9289-ce4c00fd81b7)

**Comment by DrCyanide** [comment]
Is your first screenshot accurate? It doesn't have ControlNet enabled, and it says "No Image Selected", so I don't see how it could have generated even a skeleton with what you provided.

Are you using A1111, SD.Next, or something else for your backend?

**Comment by DrCyanide** [comment]
Unable to duplicate, and after a week with no additional information I'm just going to close the ticket.
