### ISSUE TITLE
Running over local network

### ISSUE THREAD

**Issue by LaptopDev** [DrCyanide/cyanic-sd-krita#37]
My laptop doesn't have the specs to run stable diffusion on it but my server does. I normally use stable diffusion using --listen so I can access it with my laptop over my home network. Can cyanic work over my home network?

**Comment by DrCyanide** [comment]
You'll need to add `--api` to your server's startup args, but yes! I also use Krita on a laptop, so it's a feature I made sure to include. The settings section of Cyanic SD has a place to enter your server address and port number.

**Comment by LaptopDev** [comment]
Okay cool. I will try the installation

**Comment by LaptopDev** [comment]
> You'll need to add `--api` to your server's startup args, but yes! I also use Krita on a laptop, so it's a feature I made sure to include. The settings section of Cyanic SD has a place to enter your server address and port number.

Do you mount your remote server's folders with like sshfs to your laptop?
```
... for installing the extension (on linux): ...
ln -s "path_to_your_pykrita_folder/cyanic" "path_to_your_git_pull/cyanic"
ln -s "path_to_your_pykrita_folder/cyanic.desktop" "path_to_your_git_pull/cyanic.desktop"
```

**Comment by DrCyanide** [comment]
No, you don't need to mount anything from the server. Those instructions are for linking the Cyanic SD git directory to the directory that Krita expects to find plugins at - both of which would be on your laptop. There's nothing to install server side for Cyanic SD to work.

**Comment by LaptopDev** [comment]
Edit: partial woops, I didin't confirm the location of krita folder from within the UI, though I was still right about switching the link targets. After creating a new symlink, I got the dock visible now. So in fedora the location was revealed to be .local/share not usr/share.


OLD:
I believe the link command was incorrect and had the targets in each command switched around; I rewrote that part of the documentation, describing how I created the links on my linux system:

```
Create `cyanic` and `cyanic.desktop` links in `krita/pykrita/` from my repo (`cyanic-sd-krita/`) in krita's folder location on your system (command varies with installation locations):
	`ln -s */cyanic-sd-krita/cyanic */krita/pykrita/cyanic` 
	`ln -s */cyanic-sd-krita/cyanic.desktop */krita/pykrita/cyanic.desktop` 

on Fedora this might be:

	`ln -s ~/cyanic-sd-krita/cyanic.desktop /usr/share/krita/pykrita/cyanic.desktop` and
	`ln -s ~/cyanic-sd-krita/cyanic /usr/share/krita/pykrita/cyanic`

Note: `sudo` permission may be required where krita is installed to `/usr/share/` .
```
