### ISSUE TITLE
ADD sampler Schedule type

### ISSUE THREAD

**Issue by pinea00** [DrCyanide/cyanic-sd-krita#41]
Now the new version of A1111 and Forge sampler have scheduling menus. Is it possible to add the option to start the scheduler in this setting (considering that the old version does not directly add the scheduling menu)
Thanks you

**Comment by DrCyanide** [comment]
It won't be too tricky to add, but I'm towards the end of a pretty big code rewrite for the Beta version. Writing the code to support it twice isn't something I'm willing to do, so I'll be writing the changes to support it into the Beta branch.

**Comment by DrCyanide** [comment]
This code is now pushed to the Beta branch and seems to be working with the latest version of A1111. You can check out that branch if you want - that version is mostly stable, but there can be some UI hick-ups when connecting to a server that's still booting up.
