### ISSUE TITLE
(Low priority) Plugin creates a new page when inpainting

### ISSUE THREAD

**Issue by Miraihi** [DrCyanide/cyanic-sd-krita#7]
Issue: The plugin (Usually after Krita's first launch) spontaniousely create a new page (512 x 512) when attempting to inpaint. After that it functions normally.

Steps to reproduce:
0. Launch Krita
1. Create a new layer for the mask
2. Draw the mask
3. Choose the selection/layer
4. Click "generate"

**Comment by DrCyanide** [comment]
The extension loaded in the background before any document was created/loaded, and it saved that "no active document" state. When the Generate button was clicked it checked to see if there was an active document, and didn't see one, so it made one. It would've shown up for anyone in any workflow where they use the same mode (Txt2Img, Img2Img, Inpaint) they left off on last time, so it was a slightly more important bug than it first seemed.

Refreshing the active document before generating looks like it's fixed this problem. The change has been pushed.
